# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Power_Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 750)
        MainWindow.setMaximumSize(QtCore.QSize(440, 750))
        MainWindow.setStyleSheet("background-color: rgb(48, 58, 97);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RealPowerText = QtWidgets.QLineEdit(self.centralwidget)
        self.RealPowerText.setEnabled(True)
        self.RealPowerText.setGeometry(QtCore.QRect(270, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.RealPowerText.setFont(font)
        self.RealPowerText.setStyleSheet("color: rgb(255, 255, 255);")
        self.RealPowerText.setText("")
        self.RealPowerText.setObjectName("RealPowerText")
        self.ReactivePowerText = QtWidgets.QLineEdit(self.centralwidget)
        self.ReactivePowerText.setEnabled(True)
        self.ReactivePowerText.setGeometry(QtCore.QRect(270, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ReactivePowerText.setFont(font)
        self.ReactivePowerText.setStyleSheet("color: rgb(255, 255, 255);")
        self.ReactivePowerText.setText("")
        self.ReactivePowerText.setObjectName("ReactivePowerText")
        self.PowerFactorText = QtWidgets.QLineEdit(self.centralwidget)
        self.PowerFactorText.setEnabled(True)
        self.PowerFactorText.setGeometry(QtCore.QRect(270, 220, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.PowerFactorText.setFont(font)
        self.PowerFactorText.setStyleSheet("color: rgb(255, 255, 255);")
        self.PowerFactorText.setText("")
        self.PowerFactorText.setObjectName("PowerFactorText")
        self.ApparentPowerText = QtWidgets.QLineEdit(self.centralwidget)
        self.ApparentPowerText.setEnabled(True)
        self.ApparentPowerText.setGeometry(QtCore.QRect(270, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ApparentPowerText.setFont(font)
        self.ApparentPowerText.setStyleSheet("color: rgb(255, 255, 255);")
        self.ApparentPowerText.setText("")
        self.ApparentPowerText.setObjectName("ApparentPowerText")
        self.VoltageText = QtWidgets.QLineEdit(self.centralwidget)
        self.VoltageText.setEnabled(True)
        self.VoltageText.setGeometry(QtCore.QRect(270, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.VoltageText.setFont(font)
        self.VoltageText.setStyleSheet("color: rgb(255, 255, 255);")
        self.VoltageText.setText("")
        self.VoltageText.setObjectName("VoltageText")
        self.RealPowerLabel = QtWidgets.QLabel(self.centralwidget)
        self.RealPowerLabel.setGeometry(QtCore.QRect(10, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RealPowerLabel.setFont(font)
        self.RealPowerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.RealPowerLabel.setObjectName("RealPowerLabel")
        self.ReactivePowerLabel = QtWidgets.QLabel(self.centralwidget)
        self.ReactivePowerLabel.setGeometry(QtCore.QRect(10, 120, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ReactivePowerLabel.setFont(font)
        self.ReactivePowerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ReactivePowerLabel.setObjectName("ReactivePowerLabel")
        self.PowerFactorLabel = QtWidgets.QLabel(self.centralwidget)
        self.PowerFactorLabel.setGeometry(QtCore.QRect(10, 220, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PowerFactorLabel.setFont(font)
        self.PowerFactorLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.PowerFactorLabel.setObjectName("PowerFactorLabel")
        self.ApparentPowerLabel = QtWidgets.QLabel(self.centralwidget)
        self.ApparentPowerLabel.setGeometry(QtCore.QRect(10, 170, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ApparentPowerLabel.setFont(font)
        self.ApparentPowerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ApparentPowerLabel.setObjectName("ApparentPowerLabel")
        self.VoltageLabel = QtWidgets.QLabel(self.centralwidget)
        self.VoltageLabel.setGeometry(QtCore.QRect(10, 270, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.VoltageLabel.setFont(font)
        self.VoltageLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.VoltageLabel.setObjectName("VoltageLabel")
        self.ConsoleWindowLabel = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleWindowLabel.setGeometry(QtCore.QRect(10, 420, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ConsoleWindowLabel.setFont(font)
        self.ConsoleWindowLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ConsoleWindowLabel.setObjectName("ConsoleWindowLabel")
        self.CurrentLabel = QtWidgets.QLabel(self.centralwidget)
        self.CurrentLabel.setGeometry(QtCore.QRect(10, 320, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentLabel.setFont(font)
        self.CurrentLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.CurrentLabel.setObjectName("CurrentLabel")
        self.ReactiveCurrentLabel = QtWidgets.QLabel(self.centralwidget)
        self.ReactiveCurrentLabel.setGeometry(QtCore.QRect(10, 370, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ReactiveCurrentLabel.setFont(font)
        self.ReactiveCurrentLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ReactiveCurrentLabel.setObjectName("ReactiveCurrentLabel")
        self.CurrentText = QtWidgets.QLabel(self.centralwidget)
        self.CurrentText.setGeometry(QtCore.QRect(270, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.CurrentText.setFont(font)
        self.CurrentText.setStyleSheet("color: rgb(255, 255, 255);")
        self.CurrentText.setObjectName("CurrentText")
        self.ReactiveCurrentText = QtWidgets.QLabel(self.centralwidget)
        self.ReactiveCurrentText.setGeometry(QtCore.QRect(270, 370, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.ReactiveCurrentText.setFont(font)
        self.ReactiveCurrentText.setStyleSheet("color: rgb(255, 255, 255);")
        self.ReactiveCurrentText.setObjectName("ReactiveCurrentText")
        self.ConsoleWindowText = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleWindowText.setGeometry(QtCore.QRect(20, 460, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setUnderline(False)
        self.ConsoleWindowText.setFont(font)
        self.ConsoleWindowText.setStyleSheet("color: rgb(255, 255, 255);")
        self.ConsoleWindowText.setObjectName("ConsoleWindowText")
        self.ConsoleWindowLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleWindowLabel_2.setGeometry(QtCore.QRect(60, 0, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.ConsoleWindowLabel_2.setFont(font)
        self.ConsoleWindowLabel_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.ConsoleWindowLabel_2.setObjectName("ConsoleWindowLabel_2")
        self.deletebutton = QtWidgets.QPushButton(self.centralwidget)
        self.deletebutton.setGeometry(QtCore.QRect(20, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.deletebutton.setFont(font)
        self.deletebutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(232, 100, 27);")
        self.deletebutton.setObjectName("deletebutton")
        self.calculatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.calculatebutton.setGeometry(QtCore.QRect(280, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.calculatebutton.setFont(font)
        self.calculatebutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(232, 100, 27);")
        self.calculatebutton.setObjectName("calculatebutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 550, 341, 111))
        self.label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("PSUK/Resources/Brand Logo Word.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 590, 341, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("__pycache__/Brand Logo Word.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Power Calculator v2.0 by Max Ellery"))
        self.RealPowerLabel.setText(_translate("MainWindow", "Real/Active Power (kW)"))
        self.ReactivePowerLabel.setText(_translate("MainWindow", "Reactive Power (kVAr)"))
        self.PowerFactorLabel.setText(_translate("MainWindow", "Power Factor (0 - 1)"))
        self.ApparentPowerLabel.setText(_translate("MainWindow", "Apparent Power (kVA)"))
        self.VoltageLabel.setText(_translate("MainWindow", "Voltage (kV)"))
        self.ConsoleWindowLabel.setText(_translate("MainWindow", "Error Messages"))
        self.CurrentLabel.setText(_translate("MainWindow", "Current"))
        self.ReactiveCurrentLabel.setText(_translate("MainWindow", "Reactive Current"))
        self.CurrentText.setText(_translate("MainWindow", "-"))
        self.ReactiveCurrentText.setText(_translate("MainWindow", "-"))
        self.ConsoleWindowText.setText(_translate("MainWindow", "-"))
        self.ConsoleWindowLabel_2.setText(_translate("MainWindow", "Power Calculator v2.0.0 by Max Ellery"))
        self.deletebutton.setText(_translate("MainWindow", "RESET"))
        self.calculatebutton.setText(_translate("MainWindow", "CALCULATE"))
